[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
commit_parsers = [
    { message = "^feat", group = "âœ¨ FonctionnalitÃ©s"},
    { message = "^fix", group = "ğŸ› Corrections de bugs"},
    { message = "^doc", group = "ğŸ“š Documentation"},
    { message = "^perf", group = "âš¡ Performance"},
    { message = "^refactor", group = "â™»ï¸ Refactor"},
    { message = "^style", group = "ğŸ¨ Styling"},
    { message = "^test", group = "ğŸ§ª Testing"},
    { message = "^ci", group = "âš™ï¸ CI/CD"},
    { message = "^chore", skip = true},
]
protect_breaking_commits = true
filter_commits = false
tag_pattern = "^[0-9]+\\.[0-9]+\\.[0-9]+$"

topo_order = false
topo_order_commits = true
sort_commits = "oldest"
link_parsers = [
    { pattern = "#(\\d+)", href = "https://github.com/orhun/git-cliff/issues/$1"},
    { pattern = "RFC(\\d+)", text = "ietf-rfc$1", href = "https://datatracker.ietf.org/doc/html/rfc$1"},
]
recurse_submodules = false

[changelog]
header = "# Plockit - Changelog"
output = "CHANGELOG.md"