# GitVersion config compatible v6
# - Conventional commits enabled (feat => minor, fix/docs => patch)
# - Commit message incrementing enabled (recognizes "!" and "BREAKING CHANGE" as breaking)
commit-message-incrementing: Enabled

conventional-commits:
  enabled: true

mode: ContinuousDeployment

branches:
  main:
    regex: ^main$
    increment: Patch
    prevent-increment-of-merged-branch-version: true

ignore:
  sha: []