mode: ContinuousDeployment
next-version: 0.1.0

commit-message-incrementing: Enabled
commit-message-strategy: MergeMessage

major-version-bump-message: "^(!|.*!:)"
minor-version-bump-message: "^(feat|docs)"
patch-version-bump-message: "^(fix)"