mode: ContinuousDeployment
next-version: 0.1.0
commit-message-incrementing: Enabled
commit-message-strategy: MergeMessage
increment:
  major:
    regex: '^(!|.*!:)'   # commits with ! trigger major
  minor:
    regex: '^(feat|docs)'  # commits starting with feat or docs
  patch:
    regex: '^(fix|i)'   # commits starting with fix or i
