name: Déploiement vers registre

on: 
  workflow_dispatch:

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configuration de l’environnement Docker
      uses: docker/setup-docker-action@v4.5.0

    - name: Connexion au GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Construction de l’image docker
      run: docker build -t plockit .

    - name: Envoi de l’image docker sur le registre public jules-pillot.eu
      run : |
        docker tag plockit public.registry.jules-pillot.eu/plockit:$(date +'%Y-%m-%d')
        docker push public.registry.jules-pillot.eu/plockit:$(date +'%Y-%m-%d')
        docker tag plockit public.registry.jules-pillot.eu/plockit:latest
        docker push public.registry.jules-pillot.eu/plockit:latest
        docker tag plockit ghcr.io/GuGules/PlockIt:$(date +'%Y-%m-%d')
        docker push ghcr.io/GuGules/PlockIt:$(date +'%Y-%m-%d')
        docker tag plockit ghcr.io/GuGules/PlockIt:latest
        docker push ghcr.io/GuGules/PlockIt:latest