name: Génération du tag de version du changelog

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generateVersionTag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.version_step.outputs.majorMinorPatch }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.2.0
      with:
        versionSpec: '6.4.x'
    - name: Determine Version
      id: version_step # step id used as a reference for output values
      uses: gittools/actions/gitversion/execute@v4.2.0
      with:
        configFilePath: ./.github/config/gitversion.yml
    - name: Push tag to repo
      run: |
        echo "Nouvelle Version : ${{ steps.version_step.outputs.majorMinorPatch }}"
        git tag ${{ steps.version_step.outputs.majorMinorPatch }}
        git push origin ${{ steps.version_step.outputs.majorMinorPatch }}
  generateChangelog:
    needs: generateVersionTag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configuration de git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Générer et publier le changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: .github/config/cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Envoi du changelog sur le dépôt git
        run: |
         
          git add CHANGELOG.md
          git commit -m "chore: Mise à jour du changelog auto"
          git push origin main